### ISSUE TITLE
Drop Limit settings don't appear to work

### ISSUE THREAD

**Issue by geoffjukes** [panzi/ripcheck#3]
I'm having an issue changing the 'drop limit'. According to the docs:

```
-d, --drop-limit=VOLUME       set the minimum volume of samples around a drop to VOLUME
                              (default: 66.666 %)
```

So I would expect these 2 to return the same number of lines (keeping the output simple)
```
user@host$ ./ripcheck -d 66.666% test.wav | wc -l
12
user@host$ ./ripcheck test.wav | wc -l
51
```
Which makes me think it's not actually working.

**Comment by panzi** [comment]
You're right! I forgot a divide by 100 to get a ratio from the percent value. Fixed now.

**Comment by geoffjukes** [comment]
Awesome! Thanks again @panzi
